### ISSUE TITLE
Auto fill price when click on orderbook

### ISSUE THREAD

**Issue by logandinh** [project-serum/serum-dex-ui#12]
Guys, i think when users click on buy/sell order book, Serum should fill the price automatic.

it's better for users UX.

![IMG_20200907_010138_976](https://user-images.githubusercontent.com/38150663/92332167-d4e0e500-f0a5-11ea-8f32-5d711a826411.jpg)

**Comment by nishadsingh1** [comment]
Ah it currently does do that, but you have to click on the number itself (the orderbook row's size to populate the size field, price to populate price). We could make that interaction more obvious, thanks for the feedback.

**Comment by nishadsingh1** [comment]
Marking this as resolved
