### ISSUE TITLE
how to host swap ui

### ISSUE THREAD

**Issue by askmike** [project-serum/serum-dex-ui#41]
a6d753f added a SWAP link at the top of the menu, but it points to an externally hosted swap page:

https://github.com/project-serum/serum-dex-ui/blob/a6d753f0a580a421de2b13984ec2c4aa844f0472/src/components/TopBar.tsx#L48

**Comment by askmike** [comment]
it's all explained here: https://serum-academy.com/en/serum-swap/?s=09

**Comment by matt-scientist** [comment]
> https://serum-academy.com/en/serum-swap/?s=09

is there an updated link for implementing the swap ui?

**Comment by sdbarrington** [comment]
Any update on this? would be great to see an example of a serum swap GUI...
