### ISSUE TITLE
Is this depricated: https://serum-api.bonfida.com/candles/BTCUSDC?resolution=3600?

### ISSUE THREAD

**Issue by DreamITSoftware** [project-serum/serum-dex-ui#72]
I'm looking at the api docs and the candles seem to be broken, I get a 404 messages trying to use the example link
candles/BTCUSDC?resolution=3600 yields 404 page not found.

**Comment by DreamITSoftware** [comment]
This does not work either https://serum-api.bonfida.com/candles/BTCUSDC?resolution=3600

**Comment by codeislaw1993** [comment]
I have the same question

**Comment by armaniferrante** [comment]
The posted api is hosted by bonfida and isn't part of this repo. Try asking this question in their discord. https://discord.gg/T5qNny3z
