### ISSUE TITLE
Tradingview integration

### ISSUE THREAD

**Issue by radeone** [project-serum/serum-dex-ui#91]
`TypeScript error in /home/ec2-user/serum-dex-ui/src/components/TradingView/index.tsx(52,11):
Property 'container' is missing in type '{ symbol: string; datafeed: any; interval: Nominal<string, "ResolutionString">; container_id: string | undefined; library_path: string; locale: "en"; disabled_features: string[]; ... 7 more ...; theme: "Dark"; }' but required in type 'ChartingLibraryWidgetOptions'.  TS2741

    50 |
    51 |   React.useEffect(() => {
  > 52 |     const widgetOptions: ChartingLibraryWidgetOptions = {
       |           ^
    53 |       symbol: findTVMarketFromAddress(
    54 |         market?.address.toBase58() || '',
    55 |       ) as string,

error Command failed with exit code 1.
`

I have added the correct directories. Added `import { TVChartContainer } from '../../src/components/TradingView';` to TradePage.tsx, deleted the line from tsconfig.json, uncommented the `<script src="%PUBLIC_URL%/datafeeds/udf/dist/polyfills.js"></script>
<script src="%PUBLIC_URL%/datafeeds/udf/dist/bundle.js">` from index.html. Unsure what I am missing.

**Comment by radeone** [comment]
This is the error I am now getting.
![image](https://user-images.githubusercontent.com/955325/121612533-2a289900-ca20-11eb-89f9-a89999fad40b.png)

**Comment by radeone** [comment]
isolated this to an eslint issue. the readme is missing a few key steps.

**Comment by pepeneif** [comment]
Hi radeone, can you please tell us what are the missing few steps ?

Thanks!!

**Comment by pepeneif** [comment]
If anybody needs it, the answer is:

there has to be a file named:  .eslintignore

in the root directory of the project

with the following content: src/charting_library/charting_library.esm.js
