### ISSUE TITLE
Build fails with default code (without adding charts)

### ISSUE THREAD

**Issue by askmike** [project-serum/serum-dex-ui#99]
We prefer to run the UI without adding trading view charts (for licensing reasons amongst others), recent versions don't seem to compile anymore. I am not sure if this intentional (the readme hints that adding charts is optional). When trying to compile we get:

```yarn run v1.22.10
$ REACT_APP_GIT_SHA=`git rev-parse --short HEAD` REACT_APP_GIT_DATE=`git log -1 --date=format:"%Y/%m/%d" --format="%ad"` craco build
Creating an optimized production build...
Failed to compile.

./src/components/TradingView/index.tsx
Cannot find file '../../charting_library' in './src/components/TradingView'.


error Command failed with exit code 1.```

**Comment by armaniferrante** [comment]
The charts are required now, and were added here https://github.com/project-serum/serum-dex-ui/pull/98. A PR to make them optional would be great.

**Comment by askmike** [comment]
Thanks, I documented this change for now (see #100). We will try to get this sorted for our fork asap.
